"""
Django settings for idealmarket project.

Generated by 'django-admin startproject' using Django 5.2.1.
For more info, see https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# === Bazaviy katalog ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Maxfiy kalit va asosiy xavfsizlik ===
SECRET_KEY = 'django-insecure-5w-ru5mj9%88%_6q68i328)n&#w+gmbhivdsp4ioll=w*&)-0u'
DEBUG = True
ALLOWED_HOSTS = ['*']

# === Login/Logout va redirect marshrutlari ===
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# === Django ilovalari ===
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'import_export',

    # Mahalliy app
    'market',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'idealmarket.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'idealmarket.wsgi.application'

# === Ma’lumotlar bazasi (SQLite, default) ===
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# === Parol validatsiyasi ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Til va vaqt zonasi ===
LANGUAGE_CODE = 'uz-uz'         # O‘zbek tili
TIME_ZONE = 'Asia/Tashkent'     # Toshkent vaqti
USE_I18N = True
USE_TZ = True

# === Statik va media fayllar ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"  # production uchun (python manage.py collectstatic)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# === Primary key field ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# === ImportExport sozlamalari ===
IMPORT_EXPORT_USE_TRANSACTIONS = True

# === Xabarlar (Django messages) uchun Bootstrap stil ===
MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}

# === Xavfsizlik (production uchun) ===
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# SECURE_BROWSER_XSS_FILTER = True
# SECURE_CONTENT_TYPE_NOSNIFF = True

# === Loyiha uchun boshqa sozlamalar shu yerga qo‘shiladi ===

