# Generated by Django 5.2.1 on 2025-06-03 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_saleitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='s_count',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_sum',
        ),
    ]
