# Generated by Django 5.2.1 on 2025-06-03 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_end_date_product_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
