# Generated by Django 5.2.3 on 2025-06-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol (arxiv emas)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='r_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Olish narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='s_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotish narxi'),
        ),
    ]
